sudo: required
services:
  - docker

before_install:
  - docker build -t hieuna1111/docker-web -f Dockerfile.dev .

script:
  - docker run -e CI=true hieuna1111/docker-web npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'frontend'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-645410219996'
  bucket_path: 'frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY