FROM node:16-alpine

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]

# lí do thay đổi workdir thành /home/node/app để tránh lỗi permission denied, quyền root không thể chạy ở /app vì nó không có quyền ghi vào thư mục đó
# thay vì COPY . . thì COPY --chown=node:node ./ ./ để chạy với quyền của user node, tránh lỗi permission denied